services:
  postgres_students2:
    image: postgres
    container_name: postgres_students2
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env
    volumes:
      - pg_students:/var/lib/postgresql/data

  node_app:
    container_name: node_students
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres_students2
    env_file:
      - .env
volumes:
  pg_students:
